duration: 2000
experiment: AllCells
inter_group_interval: 50
mWperCell: 6
naparm_path: F:\Data\jrowland\2019-02-20\naparm\2019-01-20_blimpTest_011
num_spirals: 1
num_subsets: 1
output_path: F:\Data\jrowland\2019-02-20\blimp
percents: [90, 50]
spiral_revolutions: 5
