#### photostimulation settings ####

# path to the naparm folder containing points for experiments
naparm_path: F:\Data\jrowland\2019-04-13\naparm\2019-04-13_plasticSlide_NAPARM_001

# zoom you are imaging at, used only for spiral size
zoom: 2
# duration of each spiral (ms)
duration: 100
#number of times to repeat spirals on each cell
num_spirals: 10
# number of cells per group
group_size: 7
# power on sample / cell (18 mW is good for a burn)
# this is processed using the mw2pv matlab function which should be in the path 
mWperCell: 18
#time between groups (ms) -- should be at least 5
inter_group_interval: 30
#size of spiral (um) 
spiral_size: 15
#number of revolutions each spiral will turn
spiral_revolutions: 5

########################################################

#### behaviour settings ####

#blimp experiment to run
experiment: Subsets
#list of the percents of cells to stim in a subsets experiment
subset_sizes: [10,5]
#the number of subset permutations for a subsets experiment
#i.e. if subset_perms=3, each subset size will have 3 different
#subsets of cells to be randomly selected from
subset_perms: 1


########################################################

#### basic settings, rarely changed ####

# should be same as naparm setting
FOVsize_UM_1x: 1118.5
#path to save blimp outputs, updated automatically in startup_gui.py
output_path: F:\Data\jrowland\2019-04-13\blimp
