FOVsize_UM_1x: 1000
duration: 300
experiment: AllCells
group_size: 6
inter_group_interval: 30
mWperCell: 6
naparm_path: F:\Data\jrowland\2019-02-21\naparm\2019-02-21_blimpTest_001
num_spirals: 1
num_subsets: 1
output_path: F:\Data\jrowland\2019-02-21\blimp
percents: [90, 50]
spiral_revolutions: 5
spiral_size: 3
zoom: 4
