#### photostimulation settings ####

# path to the naparm folder containing points for experiments
naparm_path: F:\Data\jrowland\2019-06-05\naparm\2019-06-05_plasticSlide_naparm_001
#path to popt from DigitalPowerMeasurments
popt_path: E:\PowerMeasurements\2019-06-04\2019-06-04_uncaging_slm_single_spot_1030_popt.npy
#whether to recalculate phase masks, groups etc in blimp, rather than using those made in naparm
redo_naparm: False
# zoom you are imaging at, used only for spiral size
zoom: 2
# duration of each spiral (ms)
duration: 10
#number of times to repeat spirals on each cell
num_spirals: 1
# the number of times to repeat going through round each group per trial
num_repeats: 10
# number of cells per group
group_size: 40
# power on sample / cell (18 mW is good for a burn)
mWperCell: 6
#time between groups (ms) -- should be at least 5
inter_group_interval: 5
#size of spiral (um) 
spiral_size: 15
#number of revolutions each spiral will turn
spiral_revolutions: 3

########################################################

#### behaviour settings ####

#blimp experiment to run
experiment: AllCells
#the number of permuatations for each subset for a subset experiment
subset_perms: 1
#list of the number of cells to stim in a subset cells experiment
subset_sizes: [50, 40, 30, 20, 10, 5]


########################################################

#### basic settings, rarely changed ####

# should be same as naparm setting
FOVsize_UM_1x: 1118.5
#path to save blimp outputs, updated automatically in startup_gui.py
output_path: F:\Data\jrowland\2019-06-05\blimp
