duration: 500
experiment: AllCells
inter_group_interval: 50
mWperCell: 10
naparm_path: F:\Data\rlees\2019-02-04\NAPARM\2019-02-04_J007_NAPARM_001
num_spirals: 1
num_subsets: 1
output_path: F:\Data\jrowland\2019-02-06\blimp
percents: [90, 50]
spiral_revolutions: 5
